apiVersion: v1
kind: ConfigMap
metadata:
  name: pal-tracker
  labels:
    app: pal-tracker
data:
  welcome.message: "hello from kubernetes lifecycle 3"
  endpoint.exposure: "info,health,palTrackerFailure"